[package]
name = "robloxiandemo/math"
description = "A collection of very useful math-related functions, which has built-in compatiblity for usage with Wally."
version = "0.1.1"
license = "MIT"
authors = ["Demo (https://github.com/RobloxianDemo)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"